# web 환경
---
spring:
  profiles: web
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force : false
  thymeleaf.cache : false
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://homework.cxxp3pslkx1o.ap-northeast-2.rds.amazonaws.com:3306/Homework
    username: yeajihyun
    password: password